[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "resnet"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "tqdm",
    "matplotlib",
    "grad-cam",
]

[tool.setuptools]
packages = ["resnet"]
package-dir = { "resnet" = "src" }
